import { Factory, Flame, Globe, Gauge } from 'lucide-react';

export const ACL_ANALYSIS_OPTIONS = [
  'Pure salt analysis',
  'Bine analysis',
  'Pure salt seive analysis',
  'TK 203',
  'TK 204',
  'TK 205',
  'TK 207',
  'TK 209',
  'Cr 202',
  'Cr 203',
  'PCL/TCL',
  'Cacl2',
  'ACL Product',
  'ACL 300#',
  'Raw salt',
];

export const SA_ANALYSIS_OPTIONS = [
  'TK 401',
  'TK 405',
  'TK 414',
  'P 413',
  'TK 419',
  'P 417',
  'T 407',
  'T 401',
  'Bi carbonate',
  'Bi Carbonate',
  'LSA at 500#',
  'LSA',
  'E 501',
  'T 501',
  'LSA Bagging',
  'LSA Bagging sieve',
  'Gas Conc',
];

export const OFFSITE_ANALYSIS_OPTIONS = [
  'DM water',
  'BFW',
  'SHS',
  'Raw Water',
  'CBD',
  'Bottom ash',
  'FLY ash',
  'Distiller waste',
  'Vaccum seal water',
  'Sewar Water',
  'cooling water',
  'cooling water/200#',
];

export const CO2_ANALYSIS_OPTIONS = [
  'BL1204/BL1203',
  'Absorber inlet',
  'Outlet',
  'Lean',
  'Rich',
  'Washwater',
  'P1256 Cyclone',
  'Reflux',
  'Tk1251',
  'Tk1252',
  'DCC DRAIN LIQ',
  'SOX DRAIN LIQ',
  'ABSORBER DRAIN LIQ',
  'LEAN',
];

export const ALL_PLANTS_CONFIG = [
  {
    id: 'acl',
    name: 'ACL Plant',
    subtitle: 'Ammonium Chloride Unit',
    options: ACL_ANALYSIS_OPTIONS,
    badge: '15 Options',
    icon: Factory,
    color: 'blue',
  },
  {
    id: 'sa',
    name: 'SA Plant',
    subtitle: 'Soda Ash Production Unit',
    options: SA_ANALYSIS_OPTIONS,
    badge: '17 Options',
    icon: Flame,
    color: 'amber',
  },
  {
    id: 'offset',
    name: 'OFFSET Plant',
    subtitle: 'Offsite Utilities & Facilities Unit',
    options: OFFSITE_ANALYSIS_OPTIONS,
    badge: '12 Options',
    icon: Globe,
    color: 'emerald',
  },
  {
    id: 'co2',
    name: 'CO2 Plant',
    subtitle: 'Carbon Dioxide Recovery Unit',
    options: CO2_ANALYSIS_OPTIONS,
    badge: '14 Options',
    icon: Gauge,
    color: 'indigo',
  },
];
