const XLSX = require('xlsx');

/**
 * Generates an Excel (.xlsx) file buffer from report records
 * @param {Array} reports - Array of report objects
 * @param {Object} metadata - Context metadata (company name, generated by, filter parameters)
 * @returns {Buffer} Excel file buffer
 */
const generateReportsExcel = (reports, metadata = {}) => {
  // Format report data for Sheet 1
  const reportRows = reports.map((r, index) => ({
    'S.No': index + 1,
    'Report Title': r.title,
    'Report Type': r.reportType,
    'Plant': r.plantName || (r.plant ? r.plant.name : 'All Plants'),
    'Date': r.date ? new Date(r.date).toISOString().split('T')[0] : '',
    'Generated By': r.generatedByName || 'System',
    'Output (Tons)': r.metrics ? r.metrics.totalOutputTons : 0,
    'Efficiency (%)': r.metrics ? r.metrics.efficiencyPercentage : 0,
    'Downtime (Min)': r.metrics ? r.metrics.downtimeMinutes : 0,
    'Power (MWh)': r.metrics ? r.metrics.powerMWh : 0,
    'CO2 Captured (Tons)': r.metrics ? r.metrics.co2CaptureTons : 0,
    'Safety Incidents': r.metrics ? r.metrics.incidentsReported : 0,
    'Status': r.status || 'Completed',
    'Notes': r.notes || '',
  }));

  // Summary statistics for Sheet 2
  const totalOutput = reports.reduce((sum, r) => sum + (r.metrics?.totalOutputTons || 0), 0);
  const avgEfficiency = reports.length > 0 
    ? (reports.reduce((sum, r) => sum + (r.metrics?.efficiencyPercentage || 0), 0) / reports.length).toFixed(1)
    : 0;
  const totalCO2 = reports.reduce((sum, r) => sum + (r.metrics?.co2CaptureTons || 0), 0);
  const totalPower = reports.reduce((sum, r) => sum + (r.metrics?.powerMWh || 0), 0);
  const totalIncidents = reports.reduce((sum, r) => sum + (r.metrics?.incidentsReported || 0), 0);

  const summaryRows = [
    { 'Metric': 'Company Name', 'Value': metadata.companyName || 'Enterprise Analytics' },
    { 'Metric': 'Export Date', 'Value': new Date().toLocaleString() },
    { 'Metric': 'Exported By', 'Value': metadata.exportedBy || 'Administrator' },
    { 'Metric': 'Total Reports Count', 'Value': reports.length },
    { 'Metric': 'Total Production Output (Tons)', 'Value': totalOutput.toLocaleString() },
    { 'Metric': 'Average Efficiency (%)', 'Value': `${avgEfficiency}%` },
    { 'Metric': 'Total CO2 Captured (Tons)', 'Value': totalCO2.toLocaleString() },
    { 'Metric': 'Total Power Consumption (MWh)', 'Value': totalPower.toLocaleString() },
    { 'Metric': 'Total Safety Incidents Reported', 'Value': totalIncidents },
  ];

  // Create workbook and worksheets
  const wb = XLSX.utils.book_new();

  const wsReports = XLSX.utils.json_to_sheet(reportRows);
  const wsSummary = XLSX.utils.json_to_sheet(summaryRows);

  // Set column widths
  wsReports['!cols'] = [
    { wch: 6 },  // S.No
    { wch: 30 }, // Title
    { wch: 22 }, // Type
    { wch: 18 }, // Plant
    { wch: 14 }, // Date
    { wch: 20 }, // Generated By
    { wch: 14 }, // Output
    { wch: 14 }, // Efficiency
    { wch: 16 }, // Downtime
    { wch: 14 }, // Power
    { wch: 20 }, // CO2
    { wch: 16 }, // Incidents
    { wch: 12 }, // Status
    { wch: 35 }, // Notes
  ];

  wsSummary['!cols'] = [
    { wch: 35 },
    { wch: 35 },
  ];

  // Append sheets
  XLSX.utils.book_append_sheet(wb, wsReports, 'Analytics Reports');
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Executive Summary');

  // Generate buffer
  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'buffer' });
  return excelBuffer;
};

module.exports = { generateReportsExcel };
