const { Report, Company, Plant, User } = require('../models');
const { generateReportsExcel } = require('../services/excelService');

// Helper to build report query filter
const buildReportFilter = (req) => {
  const filter = {};

  // Company isolation
  if (req.user.role === 'company_admin' || req.user.role === 'user') {
    filter.company = req.user.company?._id || req.user.company;
  } else if (req.user.role === 'super_admin' && req.query.companyId) {
    filter.company = req.query.companyId;
  }

  // Filter: Plant
  if (req.query.plantId && req.query.plantId !== 'all') {
    filter.plant = req.query.plantId;
  }

  // Filter: User / Generated By
  if (req.query.userId && req.query.userId !== 'all') {
    filter.generatedBy = req.query.userId;
  }

  // Filter: Report Type
  if (req.query.reportType && req.query.reportType !== 'all') {
    filter.reportType = req.query.reportType;
  }

  // Filter: Date Range
  if (req.query.startDate || req.query.endDate) {
    filter.date = {};
    if (req.query.startDate) {
      filter.date.$gte = new Date(req.query.startDate);
    }
    if (req.query.endDate) {
      const end = new Date(req.query.endDate);
      end.setHours(23, 59, 59, 999);
      filter.date.$lte = end;
    }
  }

  // Search keyword
  if (req.query.search) {
    const s = req.query.search.trim();
    filter.$or = [
      { title: { $regex: s, $options: 'i' } },
      { generatedByName: { $regex: s, $options: 'i' } },
      { plantName: { $regex: s, $options: 'i' } },
    ];
  }

  return filter;
};

// @desc    Get reports with filtering and pagination
// @route   GET /api/reports
// @access  Private
const getReports = async (req, res) => {
  try {
    const filter = buildReportFilter(req);
    const reports = await Report.find(filter)
      .populate('plant')
      .populate('generatedBy', 'name email username')
      .populate('company', 'name code')
      .sort({ date: -1 });

    return res.status(200).json({
      success: true,
      count: reports.length,
      reports,
    });
  } catch (error) {
    console.error('Error fetching reports:', error);
    return res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Get single report details
// @route   GET /api/reports/:id
// @access  Private
const getReportById = async (req, res) => {
  try {
    const report = await Report.findById(req.params.id)
      .populate('plant')
      .populate('generatedBy', 'name email username')
      .populate('company', 'name code');

    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found.' });
    }

    return res.status(200).json({
      success: true,
      report,
    });
  } catch (error) {
    return res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Export filtered reports dynamically to Excel (.xlsx)
// @route   GET /api/reports/export/excel
// @access  Private (Super Admin, Company Admin)
const exportReportsExcel = async (req, res) => {
  try {
    const filter = buildReportFilter(req);
    const reports = await Report.find(filter)
      .populate('plant')
      .populate('generatedBy', 'name email username')
      .populate('company', 'name code')
      .sort({ date: -1 });

    const companyName = req.user.company?.name || 'All Companies';
    const excelBuffer = generateReportsExcel(reports, {
      companyName,
      exportedBy: `${req.user.name} (${req.user.role})`,
    });

    const timestamp = new Date().toISOString().slice(0, 10);
    const filename = `Analytics_Report_${companyName.replace(/[^a-zA-Z0-9]/g, '_')}_${timestamp}.xlsx`;

    res.setHeader(
      'Content-Type',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    );
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    return res.send(excelBuffer);
  } catch (error) {
    console.error('Excel export error:', error);
    return res.status(500).json({ success: false, message: 'Export failed: ' + error.message });
  }
};

// @desc    Create a new report
// @route   POST /api/reports
// @access  Private (Super Admin, Company Admin, User)
const createReport = async (req, res) => {
  try {
    const { title, reportType, plantId, period = 'Daily', metrics = {}, notes = '' } = req.body;

    if (!title || !reportType) {
      return res.status(400).json({ success: false, message: 'Title and Report Type are required.' });
    }

    let targetCompanyId = req.user.company?._id || req.user.company;
    if (req.user.role === 'super_admin') {
      targetCompanyId = req.body.companyId;
    }

    let plantName = 'All Plants';
    if (plantId) {
      const plant = await Plant.findById(plantId);
      if (plant) plantName = plant.name;
    }

    const newReport = await Report.create({
      title: title.trim(),
      reportType,
      company: targetCompanyId,
      plant: plantId || null,
      plantName,
      generatedBy: req.user._id,
      generatedByName: req.user.name,
      period,
      metrics,
      notes,
      date: new Date(),
    });

    return res.status(201).json({
      success: true,
      message: 'Report created successfully.',
      report: newReport,
    });
  } catch (error) {
    return res.status(500).json({ success: false, message: error.message });
  }
};

module.exports = {
  getReports,
  getReportById,
  exportReportsExcel,
  createReport,
};
